---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Фильтрация товаров должна быть по категориям - название, рейтинг, цена со скидкой и без нее
  - После добавления товара в корзину пользователь должен оставаться в каталоге товаров и продолжать совершать покупки
  - На странице товара и в каталоге должна отображаться следующая информация - название, рейтинг, цена со скидкой и без нее
  - На странице корзины пользователь должен иметь возможность  удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты
  - Сведения о выбранных в корзине товаров должны храниться в сессии браузера
non-functional:
  - Сайт должен быть удобным в использовании и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт магазина должен быть реализован, как SPA-приложение
implicit:
  - Сайт должен предусматривать регистрацию пользователей и хранение их персональных данных в том числе, Имя, Фамилия, телефон, эл. почта, данные о предпочитаемом способе оплаты – номер карты оплаты, срок ее действия
  - Сайт должен поддерживать взаимодействие с основными платежными системами через API
  - При реализации сайта необходим контроль за соблюдением Закона об ограничении использования персональных данных, необходимо реализовать сайт по технологиям, исключающим несанкционироваанный допуск к персональным данным
  - Сайт должен иметь защиту от SQL – инъекций и XSS – атак
  - Необходимость хранить сведения о товарах в корзине в БД после истечения сессии браузера  требования не предусматривают
