---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Фильтрация товаров должна быть по категориям - название, рейтинг, цена со скидкой и без нее
  - После добавления товара в корзину пользователь должен оставаться в каталоге товаров и продолжать совершать покупки
  - На странице товара и в каталоге должна отображаться следующая информация - название, рейтинг, цена со скидкой и без нее
  - На странице корзины пользователь должен иметь возможность  удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты
  - Сведения о выбранных в корзине товаров должны храниться в сессии браузера
non-functional:
  - Сайт должен быть удобным в использовании и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт ДОЛЖЕН БЫТЬ СОВМЕСТИМ с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах 
  - Сайт магазина должен быть реализован, как SPA-приложение
  - Сайт должен предусматривать регистрацию пользователей и хранение их персональных данных в том числе, Имя, Фамилия, телефон, эл. почта, данные о предпочитаемом способе оплаты – номер карты оплаты, срок ее действия
implicit: 
  - Пользователь должен иметь возможность сделать заказ
  - Пользователь должен иметь возможность оплатить товар
  - Пользователь должен иметь возможность увидеть цену товара в долларах и в  рублях?
  - Пользователь должен иметь возможность сбрасывать фильтр товаров
  - Сайт должен быть доступен на нескольких языках
  - Пользователь должен иметь возможность видеть товары в наличии 
  - Сайт должен поддерживать взаимодействие с основными платежными системами через API
  - При реализации сайта необходим контроль за соблюдением Закона об ограничении использования персональных данных, необходимо реализовать сайт по технологиям, исключающим несанкционироваанный допуск к персональным данным
  - Сайт должен иметь защиту от SQL – инъекций и XSS – атак
